#!/bin/bash

echo "setup"

#setup dir
sudo mkdir /rtecon
sudo chmod 777 /rtecon
sudo mkdir /rtecon/src
sudo chmod 777 rtecon/src

#git config
cd /rtecon
git init
git config --global user.name "iajomac"
git config --global user.email "iajomac@gmail.com"

#application installs
sudo yum install git
sudo yum install java-1.8.0-openjdk.x86_64
sudo yum install nginx.x86_64

echo "done"

